window_maximized = true
screen_h = 2120
screen_w = 3840
enable_damage = true
creative_mode = false
mainmenu_last_selected_world = 1
maintab_LAST = local
menu_last_game = minetest
dpi_change_notifier = 8
server_announce = false
world_config_selected_mod = 1
secure.enable_security = false

enable_server = false
